on:
  workflow_dispatch:

jobs:
  what_if:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: What-If
        run: 
          az deployment sub what-if \
            --location westeurop \
            --template-file infrastructure/main.biceps
      
